I am commit directly from the github website
because from the terminal I get this error message
Nilays-MacBook:2-lets-vote-Rapha-btc nilayatmaca$ git push -u origin master
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/Clarity-Camp/2-lets-vote-Rapha-btc.git'